# Generated by Django 2.2.4 on 2019-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_auto_20190924_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='from_example',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
