# Generated by Django 2.2.4 on 2019-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('flashcard', '0003_auto_20190926_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(related_name='entries', to='tags.Tag'),
        ),
    ]
