# Generated by Django 2.2.4 on 2019-11-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_deck_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='to_lang',
        ),
    ]
