# Generated by Django 2.2.4 on 2019-11-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_auto_20191105_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='from_example',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
